name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Report to Codecov
        run: |
          export CODECOV_TOKEN="d86b7932-0286-4c87-8ffa-31f61828f8eb"
          bash <(curl -s https://codecov.io/bash)
