name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Build Project
        run: msbuild RadikoDownloader\RadikoDownloader.csproj /p:Configuration=Release
      - name: Send Report
        run: |
          CODECOV_TOKEN="d86b7932-0286-4c87-8ffa-31f61828f8eb"
          bash <(curl -s https://codecov.io/bash)
